### ISSUE TITLE
Run on images opened in new tab

### ISSUE THREAD

**Issue by ts-web** [digimarc-corp/c2pa-content-credentials-extension#20] opened 2023-12-18 00:08 UTC
After installing the browser extension, the C2PA pin appears on the images in the github readme page, however when I load the images directly, the pin does not appear on these images.

https://raw.githubusercontent.com/digimarc-corp/c2pa-content-credentials-extension/main/docs/genai-picture-validate-protected.jpg

Is this a limitation of the Chrome browser extension API, that the code can't run on image pages?

**Comment by domguinard** [comment] 2023-12-18 15:59
Hi @ts-web - thanks a lot for reporting this. Odd indeed, we'll be looking into this. Note that I retested with v0.0.2 that was just released the and issue still appears.

**Comment by domguinard** [comment] 2023-12-19 12:47
The image works via the contentcredentials verify tool so it is not CORS: https://contentcredentials.org/verify?source=https%3A%2F%2Fraw.githubusercontent.com/digimarc-corp/c2pa-content-credentials-extension/main/docs/genai-picture-validate-protected.jpg

**Comment by ts-web** [comment] 2024-01-01 03:34
It might be related to [Chromium Issue 816121: Page CSP with sandbox blocks chrome-extension:// iframe]( https://bugs.chromium.org/p/chromium/issues/detail?id=816121).

There is an error in the console:
```
Blocked script execution in 'https://raw.githubusercontent.com/..../genai-picture-validate-protected.jpg' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

It looks like `raw.githubusercontent.com` serves the image with a CSP header:
```
Content-Security-Policy: sandbox allow-scripts allow-forms allow-popups allow-modals; script-src 'self' 'unsafe-inline' 'unsafe-eval'; child-src 'self'; worker-src 'self' blob: chrome-extension:;
```

It's confusing; maybe I'm misinterpreting it. The error says there is a frame that's sandboxed, but DevTools shows no iframes, so the "frame" must be the page itself, and the sandboxing is because of the CSP header. However, the header does say "allow-scripts" which contradicts the error message where it says "allow-scripts permission is not set". So something weird is happening.

I did try this on another image URL, and the extension did seem to load, so this issue seems to only affect urls with CSP.

I'm ok with closing this ticket and saying the extension does not support running on CSP-protected pages, until that Chromium bug is fixed. I believe it should be, because Chrome Extensions should be able to customize any page.

**Comment by PercheEtienne** [comment] 2024-01-05 15:51
Hello @ts-web,

Thank you for detailing the issue with the CSP header's sandbox directive. 
We see the extension doesn't work well with some secure pages because of their strict settings. 
We will keep an eye on this issue.

**Comment by PercheEtienne** [comment] 2024-06-17 10:21
We are closing this issue as it is not caused by our extensions but by the security policies of 'https://raw.githubusercontent.com' where the extension is used. Unfortunately, we cannot fix this issue as it falls outside our control.

**Closed by PercheEtienne** 2024-06-17 10:21 UTC
Labels: bug, wontfix
